# Generated by Django 3.2.14 on 2022-07-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('song_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='platforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformname', models.CharField(max_length=100)),
                ('platfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.songs')),
            ],
        ),
    ]
